// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5gUivCSc0DfOAdNQdOcwzEks7l6lLh2M',
    appId: '1:685670723049:web:129267f294bb8eb1e36f78',
    messagingSenderId: '685670723049',
    projectId: 'smartparking-447d3',
    authDomain: 'smartparking-447d3.firebaseapp.com',
    storageBucket: 'smartparking-447d3.firebasestorage.app',
    measurementId: 'G-7B8VKEK311',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU1t7pThjYIv7NZEs7ksr1eLEoFHRZhx0',
    appId: '1:685670723049:android:aba1bef1a57b94bde36f78',
    messagingSenderId: '685670723049',
    projectId: 'smartparking-447d3',
    storageBucket: 'smartparking-447d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFTzzAoKUqsL2JMEYpZsJ5eeXzjZXOBAQ',
    appId: '1:685670723049:ios:54b0456bda107a90e36f78',
    messagingSenderId: '685670723049',
    projectId: 'smartparking-447d3',
    storageBucket: 'smartparking-447d3.firebasestorage.app',
    iosBundleId: 'com.example.smartParkingUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFTzzAoKUqsL2JMEYpZsJ5eeXzjZXOBAQ',
    appId: '1:685670723049:ios:54b0456bda107a90e36f78',
    messagingSenderId: '685670723049',
    projectId: 'smartparking-447d3',
    storageBucket: 'smartparking-447d3.firebasestorage.app',
    iosBundleId: 'com.example.smartParkingUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5gUivCSc0DfOAdNQdOcwzEks7l6lLh2M',
    appId: '1:685670723049:web:5f74e09aee80c3f2e36f78',
    messagingSenderId: '685670723049',
    projectId: 'smartparking-447d3',
    authDomain: 'smartparking-447d3.firebaseapp.com',
    storageBucket: 'smartparking-447d3.firebasestorage.app',
    measurementId: 'G-N79QBYVWE8',
  );

}